### ISSUE TITLE
ReferenceError: global is not defined on a React app

### ISSUE THREAD

**Issue by THPubs** [influxdata/influxdb-client-js#149]
Hi! When I try to use this on a React app. I get the following error:

```
ReferenceError: global is not defined
./node_modules/@influxdata/influx/dist/index.mjs
node_modules/@influxdata/influx/dist/index.mjs:238

235 |   });
  236 | }
  237 | 
> 238 | global.setTimeout, global.clearTimeout;
  239 | var q = global.performance || {};
  240 | q.now || q.mozNow || q.msNow || q.oNow || q.webkitNow;
  241 | 
```

Any idea what's happening?

**Comment by russorat** [comment]
@THPubs thanks for opening an issue. Let me see if i can find someone to help.

**Comment by drdelambre** [comment]
@THPubs how are you including the file?
Without more context, your build pipeline (webpack, rollup, whatever is in charge of making sure that `require` works for the web) normally includes a snippet of `((_global) => { ...your code })(global || window)` around the transpiled code to ensure that the code can run both in the browser and on the server. 
This logic should most likely also be added within this library, but in the mean time, you can add `window.global = window` before including the file to get things working.

**Comment by sranka** [comment]
This client library was replaced with a new version, so this issue is outdated. Both browser and node environments are now supported. Webpack now picks up the right distribution depending on its configuration target (web or node), see 
- https://webpack.js.org/configuration/resolve/#resolvemainfields
- https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/package.json#L23
