### ISSUE TITLE
And client SDK docs?

### ISSUE THREAD

**Issue by tnolet** [influxdata/influxdb-client-js#211]
Hi, maybe I'm looking in the wrong place, but are there any docs on the client? Besides the examples, I cannot find any spec of SDK docs on this client. Kinda makes working with it impossible / very hard.

**Comment by sranka** [comment]
The API documentation is inside *d.ts files that the most used IDEs (Visual Studio Code, Web Storm) understand to do auto-completion and provide help to developers. You can generate API docs from sources.

```bash
influxdb-client-js/packages/core$ yarn build
influxdb-client-js/packages/core$ yarn typedoc
 Documentation generated at influxdb-client-js/packages/core/reports/apidoc
influxdb-client-js/packages/apis$ yarn typedoc
 Documentation generated at influxdb-client-js/packages/apis/doc/apidoc
```

**Comment by tnolet** [comment]
@sranka thanks. Would be tremendously useful and ease adoption if you could host a documentation site. Generating docs and going through source code to figure out how this works is a lot of extra work.

**Comment by tnolet** [comment]
I am a Webstorm user BTW and code completion is not nearly good enough to help here. I'm trying to figure out how to create a bucket but nothing really helps me there.

**Comment by sranka** [comment]
1. create BucketsAPI
2. bucketsAPI.postBuckets({body:{orgID,name}}
3. the js client documentation cannot be better than https://v2.docs.influxdata.com/v2.0/api/#operation/PostBuckets, which currently does not describe the parameters at all

To fully understand the issue herein. Where do you miss the documentation most... in step 1,2 or 3 ?

**Comment by tnolet** [comment]
@sranka I expect something like https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html

I use the AWS Node.js SDK heavily and their SDK docs are really helpful. Every method explained with parameters etc.

**Comment by sranka** [comment]
This is the user experience with code completion and online help with VS Code:

![vs-code-experience](https://user-images.githubusercontent.com/16321466/87818723-59b03f00-c86b-11ea-9019-a61f4408ea07.gif)

Code completion works fine, there are keyboard shortcuts the show suggestions/context and parameter/attribute/function doc (CTRL+space CTLRL+SHIFT+space in Linux). URL links in the context help are clickable. A bit more documentation in the code might still help:
- explain what is the `body` of any request
- better document API constructor + change type from any to InfluxDB (if possible)

An introduction to API concepts in the client's README will also help, it follows the same patterns in all APIs. There are 2 parts to address herein
1. improve documentation contents (continuous process), a few improvements proposed herein
2. ease the way of how to generate documentation, include general concepts of API and possibly provide online API documentation (generated gh-pages upon release)

**Comment by sranka** [comment]
@karel-rehor Can you please share your experiences/ideas from your (+ Webstorm) POV.

**Comment by tnolet** [comment]
I know what code completion is. I’ve been coding for 15 years with IDE’s. I would still love to have comprehensive documentation to help me understand the SDK, to browse and learn. 

An open source project can benefit fantastically from good documentation. I know it’s a ton of work, but code completion does not replace docs.

**Comment by sranka** [comment]
@tnolet I respect your point of view and your contribution to this issue. As the main contributor to this library, I can't pretend the first experience anymore. I asked also @karel-rehor to share his POV, I think that he reported similar problems with this library. And, yes, at the same time, I would like to minimize maintenance costs and avoid future consistency issues in the solution. My time (and also documentation skills) are limited.

The fact that the library was hard to use for the first time is still primary. Wouldn't you mind if I keep this issue open, to gather inputs and share the steps that help with a resolution of this issue?

**Comment by tnolet** [comment]
@sranka please keep the issue open if it helps! Again, good docs is hard but I’m very confident it will help Influx adoption.

**Comment by karel-rehor** [comment]
I started using influxdb-client-js about two months ago.  However, my use case was that I needed to replace axios calls to the REST api (e.g. http://localhost:9999/api/v2/) in plain js (not ts) with the cleaner and more useful client library.  So, I already had a few weeks experience working with the Influxdbv2 REST API.  The client essentially follows the model of Influxdbv2 REST and I was able to more or less intuitively find what I needed in the client API by using my knowledge of the REST model.  WebStorm autocomplete more or less confirmed what I was expecting to find based on prior REST API knowledge.

A couple of exceptions existed though.  The object structure `{body: { <properties> }}` for POST calls to create new artefacts took a while to figure out.  I was expecting just  `{<properties>}`.  (See example below).  Autocomplete in TS would have alerted me to this. Another issue was accessing and unmarshalling query results, which used an idiom with which I still have lapses (mainly idiosyncrasies of Promises).

REST API docs ornamented by ReDoc should be available at the endpoint /docs of the distribution: 

e.g.
http://localhost:9999/docs

I'm using the latest docker nightly build.

```
sudo docker pull quay.io/influxdb/influx:nightly
```

N.B. it appears the `/docs` endpoint is disabled in AWS influx cloud2.  

I agree that clear and concise documentation of basic principles can help guide first time users.  More complete documentation can be time consuming to maintain and IMHO the examples (https://github.com/influxdata/influxdb-client-js/tree/master/examples) provide sufficient technical information about how to handle essential use cases.  Though I don't see a `bucket.ts` example.  Such an example would be useful, since creating a bucket is a prerequisite for doing just about anything else, however a default  bucket should be created automatically through the `onboarding.js` example. 

Here's how I'm creating additional buckets in my test code.  

```javascript
...
const createBucket = async(orgId, // String
    orgName, //String
    bucketName, //String
) => {

    bucketAPI = new BucketsAPI(new InfluxDB({url: __config.influx_url, token: __defaultUser.token, timeout: 20000}));

    await bucketAPI.postBuckets({body: {name: bucketName, orgID: orgId}});
};
...
```

2P

**Comment by sranka** [comment]
Thank you @karel-rehor for your input, it helped. The following improvements are feasible for me to do:
1. add createBucket example
1. better explain the body parameter of the first API fn argument in all the generated APIs 
1. better document API constructor + change type from any to InfluxDB (if possible)
1. add more notes into existing examples
1. provide a better introduction to APIs in the main README.MD
1. explore the way of how to generate better documentation from existing code

**Comment by tnolet** [comment]
@sranka I would remove the whole `{ body: <properties>}` construction. It is leaking the HTTP/REST API through to you SDK. It's a leaky abstraction.

**Comment by sranka** [comment]
@tnolet ... I agree that it would look better ... the APIs are now generated from the swagger specification that we have to rely upon, it still evolves. The actual arguments can be specified in n URL path and the message body. I'll take a look of how much time would it take to merge it without the need to have optional body. In any case, such a change would require a major release.

**Comment by sranka** [comment]
Online API Reference Documentation is now available at **https://influxdata.github.io/influxdb-client-js/**
