### ISSUE TITLE
Points no longer written since version 1.6.0

### ISSUE THREAD

**Issue by P4sca1** [influxdata/influxdb-client-js#263]
Same code work fine in version 1.5.0.
Both 1.6.0 and 1.7.0 no longer write points to InfluxDB. I am using InfluxDB Cloud 2.0.
The `writeFailed` hook does not run and there is no error thrown.

```ts
const influxdb = new InfluxDB({ url, token})
const writeApi = influxdb.getWriteApi(
  config.influxdb.orgId,
  'game-server',
  's' as WritePrecision,
  {
    writeFailed(err, lines, attempts) {
      logger.error({ err, attempts }, 'Failed to write points to influxdb')
    },
  }
)
writeApi.writePoints(arrayOfPoints)
```

Example of `arrayOfPoints`:
```
[
  {
    tags: { gameServerId: '108' },
    fields: { cpuUsage: '0', memoryUsage: '0' },
    name: 'statistics',
    time: 2020-10-06T00:48:21.077Z
  },
  {
    tags: { gameServerId: '108' },
    fields: { cpuUsage: '0', memoryUsage: '0' },
    name: 'statistics',
    time: 2020-10-06T00:48:22.082Z
  },
  {
    tags: { gameServerId: '108' },
    fields: { cpuUsage: '0', memoryUsage: '0' },
    name: 'statistics',
    time: 2020-10-06T00:48:23.082Z
  },
  {
    tags: { gameServerId: '108' },
    fields: { cpuUsage: '0', memoryUsage: '0' },
    name: 'statistics',
    time: 2020-10-06T00:48:24.082Z
  },
  {
    tags: { gameServerId: '108' },
    fields: { cpuUsage: '0', memoryUsage: '0' },
    name: 'statistics',
    time: 2020-10-06T00:48:25.082Z
  },
  {
    tags: { gameServerId: '108' },
    fields: { cpuUsage: '0', memoryUsage: '0' },
    name: 'statistics',
    time: 2020-10-06T00:48:26.082Z
  },
  {
    tags: { gameServerId: '108' },
    fields: { cpuUsage: '0', memoryUsage: '0' },
    name: 'statistics',
    time: 2020-10-06T00:48:27.082Z
  },
  {
    tags: { gameServerId: '108' },
    fields: { cpuUsage: '0', memoryUsage: '0' },
    name: 'statistics',
    time: 2020-10-06T00:48:28.082Z
  },
  {
    tags: { gameServerId: '108' },
    fields: { cpuUsage: '0', memoryUsage: '0' },
    name: 'statistics',
    time: 2020-10-06T00:48:29.087Z
  },
  {
    tags: { gameServerId: '108' },
    fields: { cpuUsage: '0', memoryUsage: '0' },
    name: 'statistics',
    time: 2020-10-06T00:48:30.086Z
  },
  {
    tags: { gameServerId: '108' },
    fields: { cpuUsage: '0', memoryUsage: '0' },
    name: 'statistics',
    time: 2020-10-06T00:48:31.088Z
  }
]
```

Here is how I create the points:
```ts
const cpuAndMemoryUsagePoints = statistics.cpuAndMemoryUsage.map(
  (stat) =>
    new Point('statistics')
      .tag('gameServerId', gameServer.id.toString())
      .floatField('cpuUsage', stat.cpuUsage)
      .floatField('memoryUsage', stat.memoryUsage)
      .timestamp(stat.time)
)

const playerCountPoints = statistics.playerCount.map((stat) =>
  new Point('statistics')
    .tag('gameServerId', gameServer.id.toString())
    .intField('playerCount', stat.playerCount)
    .timestamp(stat.time)
)
```

**Comment by sranka** [comment]
Thank you for reporting an issue. I tried hard, but I can't reproduce this with 1.7.0 and a modified write Example:

```js
...
      const url='https://eu-central-1-1.aws.cloud2.influxdata.com'
      const token='MY_TOKEN'
      const org='MY_USER'
...
function writeExample(value) {
        const config = {
          writeFailed: function(err, lines, attempts) {
              console.error('WRITEFAILED',{ err, lines, attempts }, `${new Date().toISOString()} - failed to write points to influxdb`)
          }          
        }
        const writeApi = influxDB.getWriteApi(org, bucket, 'ms',  config)
        // setup default tags for all writes through this API
        writeApi.useDefaultTags({location: 'browser'})

        log('\n*** WRITE ***')
        const point1 = new Point('temperature')
          .tag('example', 'index.html')
          .floatField('value', value)
        writeApi.writePoint(point1)
        log(` ${point1.toLineProtocol()}`)

        // flush pending writes and close writeApi
        writeApi
          .flush()
          .then(() => {
            log('WRITE FINISHED')
            temperatureInput.value = String(20 + Math.round(100 * Math.random()) / 10)
          })
          .catch(e => {
            log('WRITE FAILED', e)
          })
      }
```
The exact steps I used:

1. start with a local copy of https://github.com/influxdata/influxdb-client-js
1. cd examples, modify connection parameters and `writeExample` function in index.html
1. rm -rf node_modules
1. yarn install
1. yarn browser
1. open http://localhost:3001/examples/index.html in Firefox 80
1. Click `Write` 

If I open the browser console, there are the following logs proving that `writeFailed` is called:

```
WRITEFAILED Object { err: TypeError, lines: (1) […], attempts: 1 } 2020-10-06T03:11:38.037Z - failed to write points to influxdb WARN: Write to InfluxDB failed (remaining attempts: 3). TypeError: NetworkError when attempting to fetch resource. WRITE FAILED 
WRITEFAILED Object { err: TypeError, lines: (1) […], attempts: 2 } 2020-10-06T03:11:43.090Z - failed to write points to influxdb WARN: Write to InfluxDB failed (remaining attempts: 2). TypeError: NetworkError when attempting to fetch resource. 
WRITEFAILED Object { err: TypeError, lines: (1) […], attempts: 3 } 2020-10-06T03:12:08.276Z - failed to write points to influxdb WARN: Write to InfluxDB failed (remaining attempts: 1). TypeError: NetworkError when attempting to fetch resource. WRITEFAILED Object { err: TypeError, lines: (1) […], attempts: 4 } 2020-10-06T03:14:13.412Z - failed to write points to influxdb ERROR: Write to InfluxDB failed. TypeError: NetworkError when attempting to fetch resource.
```

A few things have changed regarding write functionality from browser since 1.5, they could possibly affect the way of how your code works, but they do not explain why `writeFailed` is not called:
- https://github.com/influxdata/influxdb-client-js/pull/233 - default retry strategy has changed, there are 3 retries after 5, 25, and 125 seconds (shown in the logs above)
- https://github.com/influxdata/influxdb-client-js/pull/246 - ensures that a closed WriteApi cannot be used anymore, an exception is thrown to the client then
- https://github.com/influxdata/influxdb-client-js/pull/242 - fixed serialization of the backslash character to line protocol (applies only when a backslash is used in field/tag values) 

https://github.com/influxdata/influxdb-client-js/issues/262 is still an open defect in the cloud, the client currently does not work from Firefox and Safari, a workaround is provided. The `writeFailed` callback is however called in this situation.

May I ask you to test this using an isolated example, report the browser version that you used, inspect the communication from the browser to the cloud (if it happens), take a look at the browser console if it does not indicate some other error?

**Comment by P4sca1** [comment]
I use the influx client in node.js 10.
The writeAPI is created once on application start and never manually closed as it acts as a daemon and collects and sends data every minute.
I noticed that you are using a different url in your example. Here’s what I am using: https://eu-central-1-1.aws.cloud2.influxdata.com/api/v2

**Comment by P4sca1** [comment]
I changed the url to https://eu-central-1-1.aws.cloud2.influxdata.com and it is now working with 1.7.0 again.
Something seems to have changed from `1.5.0` to `1.6.0` which requires to leave out the `/api/v2` suffix in the url option.
Still weird that `writeFailed` was not called.

**Comment by sranka** [comment]
OK then. [#238](https://github.com/influxdata/influxdb-client-js/pull/238) wasa fix that respects context path in client's url option so that any proxies can be possibly used.  Please change your URL to `https://eu-central-1-1.aws.cloud2.influxdata.com` .
When I use `/api/v2` suffix in url, writefailed fn is called once with err: 405 Method Not Allowed .
```

**Comment by P4sca1** [comment]
If I understand correctly I was sending write requests to the api endpoint `https://eu-central-1-1.aws.cloud2.influxdata.com/api/v2/api/v2/write`. Shouldnt this result in `writeFailed` being called with a `NetworkError` as this endpoint does not exist? I spent a long time trying to figure out why my data is no longer written. An error would've helped drastically.

**Comment by sranka** [comment]
I found the root cause of why `writeFailed` was not called. If the client is configured with `https://eu-central-1-1.aws.cloud2.influxdata.com/api/v2`, the client library makes HTTP POST to `/api/v2/api/v2/write`. This unexpectedly **succeeds** with 200 status code and response data:
```
{"authorizations":"/api/v2/authorizations","backup":"/api/v2/backup","buckets":"/api/v2/buckets","checks":"/api/v2/checks","dashboards":"/api/v2/dashboards","delete":"/api/v2/delete","external":{"statusFeed":"https://www.influxdata.com/feed/json"},"flags":"/api/v2/flags","labels":"/api/v2/labels","me":"/api/v2/me","notificationEndpoints":"/api/v2/notificationEndpoints","notificationRules":"/api/v2/notificationRules","orgs":"/api/v2/orgs","plugins":"/api/v2/telegraf/plugins","query":{"analyze":"/api/v2/query/analyze","ast":"/api/v2/query/ast","self":"/api/v2/query","suggestions":"/api/v2/query/suggestions"},"scrapers":"/api/v2/scrapers","setup":"/api/v2/setup","signin":"/api/v2/signin","signout":"/api/v2/signout","sources":"/api/v2/sources","swagger":"/api/v2/swagger.json","system":{"debug":"/debug/pprof","health":"/health","metrics":"/metrics"},"tasks":"/api/v2/tasks","telegrafs":"/api/v2/telegrafs","users":"/api/v2/users","variables":"/api/v2/variables","write":"/api/v2/write"}
```

I would rather improve the client to check that the response status code is 204 (https://docs.influxdata.com/influxdb/v2.0/api/#operation/PostWrite ), so that 200 will no longer be OK :shrug:. I will keep this defect open until that happens.

**Comment by P4sca1** [comment]
Alright, thanks for your time! :)
