### ISSUE TITLE
deleteAPI.postDelete - 501: not implemented'

### ISSUE THREAD

**Issue by mprevide** [influxdata/influxdb-client-js#278]
__Expected Behavior:__

Delete the measurement

__Current Behavior:__

'501: not implemented'

__Possible Solution:__

__Steps/Code to Reproduce the Problem:__

```
// ...
      await this.deleteAPI.postDelete({
        org,
        bucket,
        body: {
          predicate: `_measurement="${measurement}"`,
          start: '1970-01-01T00:00:00Z',
          stop: new Date().toISOString(),
        },
      });
```

__Specifications:__

- Version: 1.8.0
- Platform:

**Comment by sranka** [comment]
Thank you for posting an issue, this error probably depends on the InfluxDB server version. The client APIs were generated from [swagger.yaml](https://github.com/influxdata/influxdb/blob/master/http/swagger.yml) on September 15th, the swagger definition file and the InfluxDB server changed since then. The latest InfluxDB does not include the /delete operation anymore, so it should not be in the client. 

The client APIs will be regenerated in the release.
