### ISSUE TITLE
Using a single client to query and write to multiple organisations

### ISSUE THREAD

**Issue by shirish87** [influxdata/influxdb-client-js#282]
__Proposal:__

Current client API design only allows supplying the auth token at the time of creating the "InfluxDB" instance (i.e. `new InfluxDB({ url: "...", token: "..." });`)

Please correct me if I'm wrong, but my understanding, at least from using the OSS version v2.0.1, is that each token ("Read/Write" as well a "All access") is bound to a particular org. If I supply a token to the constructor of `InfluxDB`, that client instance can practically only query the org that token was generated for. So, `getWriteApi(...)` and `getQueryApi(...)` accepting `org` as a parameter, but not `token` is restrictive, imo.

__Current behavior:__

Although I can create an `InfluxDB` instance without a token, not sure how to supply an org-specific token on a per-org basis for each query or write request.

__Desired behavior:__

So that I could use `org` or `bucket` specific tokens for every dispatched request, having the *Api instances override [auth token config](https://github.com/influxdata/influxdb-client-js/blob/eb3bbf264cc7e9172d4e65cc9be5b3dd74646186/packages/core/src/impl/node/NodeHttpTransport.ts#L180) would help.

```
getWriteApi(org: string, bucket: string, token?: string, precision?: WritePrecisionType, writeOptions?: Partial<WriteOptions>): WriteApi;

getQueryApi(org: string, token?: string): QueryApi;
```

__Alternatives considered:__
* using one client instance per org/token

__Use case:__
Using a single client instance:
* to query and write to multiple organisations
* to use particular tokens for writing to/querying specific buckets

**Comment by sranka** [comment]
Thank you for reporting an issue. Yes, there is no possibility to have the same auth token for more organizations in InfluxDB. The present client-js API design is suitable for typical use-cases that involve a single organization and a specific authentication token. An immutable authentication token is part of a code invariant that can hardly be changed, especially because of the asynchronous batching nature of WriteApi. I understand that it might be restrictive in routing use cases.

As you already know, you can still instantiate multiple InfluxDB instances and their Apis. The InfluxDB objects, as well as API instances, have a small memory footprint and are quick to instantiate. Be careful however with the WriteApi instances that can flush data asynchronously and buffers data to write under the hood, these must be closed properly. You can pool the instances that you create.

I can imagine adding `transportHeaders` to `QueryOptions` and `WriteOptions`, so you could possibly overwrite the token when creating a specific Write/Query API as follows: 
```
getWriteApi(org, bucket, precision, {transportHeaders: {authorization: `Token ${per_api_token}`}})
```
Is this something that you would welcome?

**Comment by shirish87** [comment]
Yes!

I have something like [this](https://gist.github.com/shirish87/5bf18923ec48e36beae9a3c27db70b37#file-influxdb-ts-L75) set up at the moment.

**Comment by sranka** [comment]
@shirish87 https://github.com/influxdata/influxdb-client-js/pull/283 adds `headers` to WriteOptions and QueryOptions. Take a look, approve the change if this is it. Custom authentication headers is unit-tested in

https://github.com/influxdata/influxdb-client-js/pull/283/files#diff-b99453a478880e5a618d7ac53139cad577be93beccff27f87dfecaf62b09b71aR382

and

https://github.com/influxdata/influxdb-client-js/pull/283/files#diff-adc291cb9997ec64860daae52257108419e771cfad10ce9f031e191bdb8cbefeR226

**Comment by sranka** [comment]
@shirish87 `1.9.0-nightly.1006` version of `@influxdata/influxdb-client` allows specifying custom headers

**Comment by shirish87** [comment]
I  can confirm that this works as expected. Thank you, @sranka, for the quick response! :100: :+1: :1st_place_medal: 

On another note, would you consider having `WriteApi` accept `Observable<Point>`? atm, I was thinking of using RxJS as follows:

```
  write(points$: Observable<Point>): Subscription {
    return points$
      .pipe(finalize(async () => await this.writeApi.flush(true)))
      .subscribe((pt) => this.writeApi.writePoint(pt));
  }
```

`QueryApi.rows(...): Observable<Row>` is a really convenient! Thanks.

**Comment by sranka** [comment]
A few lines of code with observable operators realize the needs, these lines might a bit vary from your approach to better match the expectation of the user. The simplest valid implementation can be as simple as `points.subscribe(writeApi.writePoint)`. I would rather do not impose a specific way of how to write/pipe from observable (of points or rows), it becomes more clear of what is happening if the code is a bit more verbose. 

Once [Observable](https://github.com/tc39/proposal-observable) moves closer to the EcmaScript standard, I can rethink my approach.
