### ISSUE TITLE
Unable to programatically write points : TOO MANY FILES OPEN

### ISSUE THREAD

**Issue by noob-master147** [influxdata/influxdb-client-js#453]
Im trying to write points to Influx but this keeps happening 
`unexpected error writing points to database: too many open files`

![image](https://user-images.githubusercontent.com/43108912/172832411-92e3bdc3-03ea-4f34-8732-808bae94ffdc.png)

the code algorithm is  this
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/43108912/172833520-64721abb-2757-42b2-988a-1216370d93f7.png">

there are only 3 orgs and some 2000 activities in total, Influx is not able to handle 2000 write operations? 
Also I need to do this same operation for over 2 million activities spread over 100s of orgs

**Comment by sranka** [comment]
This defect is returned by InfluxDB ... and is caused by your operating system that limits the number of opened files. You have to increase the limit for the user that runs your InfluxDB. Please take a look at https://github.com/influxdata/influxdb/issues/9871#issuecomment-390332769 as a starting point. Feel free to ask the InfluxDB community if you get stuck with it.

**Comment by noob-master147** [comment]
Thanks @sranka 
I increased The maximum number of open file descriptors by running `ulimit -n 99999`
that did solve the previous issue, but now its throwing a diff issue

![image](https://user-images.githubusercontent.com/43108912/172838324-f5c14ab1-fbd3-4b43-a14f-d32f22683b9d.png)
